# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DSP_TEST/DSP_TEST.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_TEST || ORIG_REF_NAME==DSP_TEST} -quiet] -quiet

# IP: bd/DSP_TEST/ip/DSP_TEST_dds_compiler_0_0/DSP_TEST_dds_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_TEST_dds_compiler_0_0 || ORIG_REF_NAME==DSP_TEST_dds_compiler_0_0} -quiet] -quiet

# IP: bd/DSP_TEST/ip/DSP_TEST_dds_compiler_0_1/DSP_TEST_dds_compiler_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_TEST_dds_compiler_0_1 || ORIG_REF_NAME==DSP_TEST_dds_compiler_0_1} -quiet] -quiet

# IP: bd/DSP_TEST/ip/DSP_TEST_mult_gen_0_0/DSP_TEST_mult_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_TEST_mult_gen_0_0 || ORIG_REF_NAME==DSP_TEST_mult_gen_0_0} -quiet] -quiet

# XDC: bd/DSP_TEST/DSP_TEST_ooc.xdc
