######################################################################
#
# File name : DSP_TEST_wrapper_compile.do
# Created on: Mon May 07 16:50:44 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xbip_utils_v3_0_9
vlib modelsim_lib/msim/axi_utils_v2_0_5
vlib modelsim_lib/msim/xbip_pipe_v3_0_5
vlib modelsim_lib/msim/xbip_bram18k_v3_0_5
vlib modelsim_lib/msim/mult_gen_v12_0_14
vlib modelsim_lib/msim/xbip_dsp48_addsub_v3_0_5
vlib modelsim_lib/msim/xbip_dsp48_multadd_v3_0_5
vlib modelsim_lib/msim/dds_compiler_v6_0_16
vlib modelsim_lib/msim/xil_defaultlib

vmap xbip_utils_v3_0_9 modelsim_lib/msim/xbip_utils_v3_0_9
vmap axi_utils_v2_0_5 modelsim_lib/msim/axi_utils_v2_0_5
vmap xbip_pipe_v3_0_5 modelsim_lib/msim/xbip_pipe_v3_0_5
vmap xbip_bram18k_v3_0_5 modelsim_lib/msim/xbip_bram18k_v3_0_5
vmap mult_gen_v12_0_14 modelsim_lib/msim/mult_gen_v12_0_14
vmap xbip_dsp48_addsub_v3_0_5 modelsim_lib/msim/xbip_dsp48_addsub_v3_0_5
vmap xbip_dsp48_multadd_v3_0_5 modelsim_lib/msim/xbip_dsp48_multadd_v3_0_5
vmap dds_compiler_v6_0_16 modelsim_lib/msim/dds_compiler_v6_0_16
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom -64 -93 -work xbip_utils_v3_0_9  \
"../../../../DSP_TEST.srcs/sources_1/bd/DSP_TEST/ipshared/a5f8/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work axi_utils_v2_0_5  \
"../../../../DSP_TEST.srcs/sources_1/bd/DSP_TEST/ipshared/ec8e/hdl/axi_utils_v2_0_vh_rfs.vhd" \

vcom -64 -93 -work xbip_pipe_v3_0_5  \
"../../../../DSP_TEST.srcs/sources_1/bd/DSP_TEST/ipshared/442e/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work xbip_bram18k_v3_0_5  \
"../../../../DSP_TEST.srcs/sources_1/bd/DSP_TEST/ipshared/c08f/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work mult_gen_v12_0_14  \
"../../../../DSP_TEST.srcs/sources_1/bd/DSP_TEST/ipshared/6bb5/hdl/mult_gen_v12_0_vh_rfs.vhd" \

vcom -64 -93 -work xbip_dsp48_addsub_v3_0_5  \
"../../../../DSP_TEST.srcs/sources_1/bd/DSP_TEST/ipshared/ad9e/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work xbip_dsp48_multadd_v3_0_5  \
"../../../../DSP_TEST.srcs/sources_1/bd/DSP_TEST/ipshared/cd0f/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work dds_compiler_v6_0_16  \
"../../../../DSP_TEST.srcs/sources_1/bd/DSP_TEST/ipshared/a2f9/hdl/dds_compiler_v6_0_vh_rfs.vhd" \

vcom -64 -93 -work xil_defaultlib  \
"../../../../DSP_TEST.srcs/sources_1/bd/DSP_TEST/ip/DSP_TEST_dds_compiler_0_0/sim/DSP_TEST_dds_compiler_0_0.vhd" \
"../../../../DSP_TEST.srcs/sources_1/bd/DSP_TEST/ip/DSP_TEST_dds_compiler_0_1/sim/DSP_TEST_dds_compiler_0_1.vhd" \
"../../../../DSP_TEST.srcs/sources_1/bd/DSP_TEST/ip/DSP_TEST_mult_gen_0_0/sim/DSP_TEST_mult_gen_0_0.vhd" \

vlog -64 -incr -work xil_defaultlib  \
"../../../../DSP_TEST.srcs/sources_1/bd/DSP_TEST/sim/DSP_TEST.v" \
"../../../../DSP_TEST.srcs/sources_1/bd/DSP_TEST/hdl/DSP_TEST_wrapper.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

