######################################################################
#
# File name : tb_top_wave.do
# Created on: Mon May 07 18:14:47 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
